application: hyprtv
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /autofollow
  script: autofollow.py

- url: /processdms
  script: CommandsProcessor.py

derived_file_type:
- python_precompiled